sonar.projectName=LMS System
sonar.sources=backend-flask
sonar.tests=backend-flask
sonar.exclusions=**/coverage/**
sonar.test.inclusions=**/test_*.py
sonar.python.coverage.reportPaths=backend-flask/coverage.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10